//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroAPI.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HeroMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HeroMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HeroAPI.Messages.HeroMessages", typeof(HeroMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero id.
        /// </summary>
        public static string HeroId {
            get {
                return ResourceManager.GetString("HeroId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to enter &apos;hero id&apos;.
        /// </summary>
        public static string HeroIdRequired {
            get {
                return ResourceManager.GetString("HeroIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero name.
        /// </summary>
        public static string HeroName {
            get {
                return ResourceManager.GetString("HeroName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to enter &apos;hero name&apos;.
        /// </summary>
        public static string HeroNameRequired {
            get {
                return ResourceManager.GetString("HeroNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hero power.
        /// </summary>
        public static string HeroPower {
            get {
                return ResourceManager.GetString("HeroPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required to enter &apos;hero power&apos;.
        /// </summary>
        public static string HeroPowerRequired {
            get {
                return ResourceManager.GetString("HeroPowerRequired", resourceCulture);
            }
        }
    }
}
